version: '3'
services:
  web:
    build: .
    container_name: turn_on_server
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
      - ${HOME}/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
    restart: always
